kernel:
  image: linuxkit/kernel:5.4.39
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0 docker_registry=192.168.1.1 grpc_authority=192.168.1.1:42113 grpc_cert_url=http://192.168.1.1:42114/cert packet_base_url=http://192.168.1.2/workflow tinkerbell=http://192.168.1.1 registry_username=admin registry_password=ce51b0ca1f13febf18938ecd4c4ad81c69c7651551a21a7642794d025ce1d869"
init:
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8
  - linuxkit/ca-certificates:v0.8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  - name: sysfs
    image: linuxkit/sysfs:v0.8
  - name: format
    image: linuxkit/format:v0.8
  - name: mount
    image: linuxkit/mount:v0.8
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
  - name: ntpd
    image: linuxkit/openntpd:v0.8
  - name: docker
    image: tink-docker:0.0
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
     - /var/run/docker:/var/run
    runtime:
      mkdir:
        - /var/run/docker
  - name: bootkit
    image: bootkit:0.0
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/run/docker:/var/run
     - /var/run/worker:/worker
    runtime:
      mkdir:
        - /var/run/docker
        - /var/run/worker
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
