name: For each commit
on:
  push:
    paths-ignore:
      - kernel/**
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to quay.io
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Figure Commit Short ID
        id: commitid
        run: |
          echo ::set-output name=short::$(git rev-parse --short HEAD)

      - name: Build and push hook-bootkit
        uses: docker/build-push-action@v3
        with:
          context: ./hook-bootkit/
          platforms: linux/amd64,linux/arm64
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: quay.io/tinkerbell/hook-bootkit:latest,quay.io/tinkerbell/hook-bootkit:sha-${{steps.commitid.outputs.short}}

      - name: Build and push hook-docker
        uses: docker/build-push-action@v3
        with:
          context: ./hook-docker/
          platforms: linux/amd64,linux/arm64
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: quay.io/tinkerbell/hook-docker:latest,quay.io/tinkerbell/hook-docker:sha-${{steps.commitid.outputs.short}}

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Fetch Nix Deps
        run: nix-shell --command true

      - name: Run formatters and linters
        run: nix-shell --run .github/workflows/formatters-and-linters.sh

      - name: Build & Deploy
        run: |
          ./hack/build-and-deploy.sh
          TAG=sha-${{steps.commitid.outputs.short}} ./hack/build-and-deploy.sh

      - uses: actions/upload-artifact@v3
        with:
          name: hook-${{steps.commitid.outputs.short}}.tar.gz
          path: hook-${{steps.commitid.outputs.short}}.tar.gz
